### ISSUE TITLE
EEPROM resolution incorrect on SSD1608 pHAT?

### ISSUE THREAD

**Issue by jerbzz** [pimoroni/inky#102]
Hi,

When running `identify.py` from the examples, I get this output on my two pHATs:

```
$ sudo ./identify.py
Found: Red pHAT (High-Temp)
Display: 212x104
Color: red
PCB Variant: 1.2
Display Variant: 1
Time: 2020-09-01 16:39:46.9
```
```
$ sudo ./identify.py
Found: Yellow pHAT (SSD1608)
Display: 212x104
Color: yellow
PCB Variant: 1.2
Display Variant: 12
Time: 2020-10-08 17:17:35.9
```
The resolution for the Yellow (SSD1608) pHat is incorrect - it should be 250x122.

I can see that the resolution appears to be read directly from the EEPROM in `eeprom.py`. The class instance returned from inky.auto does return the correct resolution/width/height for both boards, but this appears to be hardcoded in `phat.py` and elsewhere.

Not sure how much this matters, but it bothered me 😁

**Comment by Gadgetoid** [comment]
I'll raise this with production, I think the EEPROM data was prepared before we had the pleasant surprise of discovering the display was higher resolution... yep suddenly finding out your display is a different resolution to the old part is a thing that happens with E-Ink :laughing:
