### ISSUE TITLE
Issue with Pillow 8.3

### ISSUE THREAD

**Issue by Sebwap** [pimoroni/inky#116]
Inky library does'nt work anymore with last Pillow version (8.3) which has an issue with Numpy, as mentionned here:

https://github.com/python-pillow/Pillow/issues/5571

A workaround is provided in this link, maybe it should be implemented before next Pillow upgrade ?

Thanks :)

**Comment by Sebwap** [comment]
Issue in Pillow will be corrected soon in Pillow 8.3.1.

**Comment by Gadgetoid** [comment]
Thank you!
