### ISSUE TITLE
Issues with running this out of the box - 7-Colour (UC8159) Inky Impression

### ISSUE THREAD

**Issue by fotosyn** [pimoroni/inky#123]
I had success getting this to run on an older build of Raspberry Pi OS; yet I want to be able to do this from new. I have created some image capture / processing scripts which I cannot get to work on my Raspberry Pi 4B

I have a Pi Zero with a previous version of Raspberry Pi OS and things run fine.

Problem:

I have a freshly / brand new install of Raspberry Pi OS

```
pi@raspberrypi:~ $ cat /etc/debian_version
10.9

pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

I downloaded the Pimoroni libraries from here as instructed. Ends up like this:

```
Downloading examples and documentation...
Resources for your Inky pHAT & wHAT were copied to
/home/pi/Pimoroni/inky

Finalising Install...

Some packages could not be installed, review the output for details!
```

I enabled I2C in raspsi-config, after receiving this error when I tried `python3 identify.py`:

```
modprobe: FATAL: Module i2c-dev not found.
```

Checked my kernel version after `sudo rpi-update`:

```
Linux raspberrypi 5.10.60-v7l+ #1448 SMP Sat Aug 21 10:45:41 BST 2021 armv7l GNU/Linux
```

After a reboot, I trued the following with `python3 identify.py`  again:

```
pi@raspberrypi:~/Pimoroni/inky/examples $ python3 identify.py 
Found: 7-Colour (UC8159)
Display: 600x448
Color: None
PCB Variant: 1.2
Display Variant: 14
Time: b'2021-05-18 11:57:40.8'
```

All good. Then I try `python3 logo.py` - No dice

```
pi@raspberrypi:~/Pimoroni/inky/examples $ python3 logo.py
Inky pHAT/wHAT: Logo

Displays the Inky pHAT/wHAT logo.

Detected 7-Colour (UC8159)
pi@raspberrypi:~/Pimoroni/inky/examples $
```

Script runs and completes successfully, but the Inky Impression does not update. Same for any of the examples. Almost like a graceful failure with no verbose reporting.

Unplug the Inky and connect to my Pi Zero which has a previous version of Raspberry Pi OS / Raspbian (Buster). Works fine. Swap SD cards into the Pi 4 I've been trying with swapping out the new card for the one from the Zero. 

Again works fine with the card from the Pi Zero and older OS. Which is cool. But.... I want to be able to document this in part of my deployment of some scripts, and it appears I cannot get this to work on a fresh install with recent updates. 

I don't want to target legacy builds to get this working, even for your examples.

I'm sure you've been asked this already; and I have seen some references but none of the advice seemed to work. Can you help?

**Comment by helgibbons** [comment]
Closing as Inky should hopefully now be playing nicely with Bullseye - let us know if you're still having problems!
