### ISSUE TITLE
Inky wHAT Yellow not detected on Raspberry PI Zero W

### ISSUE THREAD

**Issue by mfloryan** [pimoroni/inky#124]
Raspberry Pi Zero W v1.1 with updated Raspbian Lite (5.10.60+) with a new inky wHAT Yellow.

The `identify.py` just returns `No display EEPROM detected`.
Running something like `./quotes-what.py --colour yellow` shows no errors but the display doesn't change (It still shows the original logo). 
`SPI` and `I2C` are enabled. I run the `inky` install script with no errors.

Is there a way to diagnose the display in any way?

**Comment by arjology** [comment]
having the same issue and i2c doesn't seem to show anything either

`i2cdetect -y 2`
```
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```
