### ISSUE TITLE
Grainy Image issue

### ISSUE THREAD

**Issue by Ikana** [pimoroni/inky#125]
I used the code on the example with little modification but when I display an image that I downloaded from unsplash the images are always grainy.
![7bd0af8b9b44c1c3e4b2b587fb4176b302e39eeb_2_666x500](https://user-images.githubusercontent.com/634704/131343893-9da14b88-3e5e-47a3-a3ad-78309781bc0d.jpg)

**Comment by Gadgetoid** [comment]
That’s the library attempting to convert a RGB image into a paletted one for display- the grain you’re seeing is dithering which looks terrible if it’s trying to approximate a solid colour.

You need to convert the images into 8bit PNG or another palette format with the correct colour order for them to display without automatic dithering occurring.

I go into a little bit more detail about how it all works here, but when converting your image it’s the *order* of the colours that matters and not the specific colours themselves - https://github.com/pimoroni/inky/issues/115
