### ISSUE TITLE
Important bug fix (for #93) isn't included in latest release. 

### ISSUE THREAD

**Issue by tomcobley** [pimoroni/inky#128]
@bencobley and I just had a similar problem to the one in #93 when using the `pip3` package, and came to the same fix before I found the issue and PR. It seems like the fix (#120) hasn't been included in a release yet, so it's probably still causing problems for other users as well. 

It would be great to get a new release out to fix this.

**Comment by Gadgetoid** [comment]
This is now in v1.3.0!
