### ISSUE TITLE
New issues with running this out of the box - 7-Colour (UC8159) Inky Impression

### ISSUE THREAD

**Issue by iskopa** [pimoroni/inky#146]
Hello,

I have connected the inky impression to a raspi 3 running raspberry py OS and installed the inky libraries using:

curl https://get.pimoroni.com/inky | bash

when I execute 

/Pimoroni/inky/examples/7color $ python clear.py
Detected 7-Colour (UC8159)
/usr/local/lib/python3.9/dist-packages/inky/inky_uc8159.py:313: UserWarning: Busy Wait: Timed out after 1.01s
  warnings.warn("Busy Wait: Timed out after {:0.2f}s".format(time.time() - t_start))
/usr/local/lib/python3.9/dist-packages/inky/inky_uc8159.py:313: UserWarning: Busy Wait: Timed out after 0.20s
  warnings.warn("Busy Wait: Timed out after {:0.2f}s".format(time.time() - t_start))

This is my system:

ubuntu@raspberrypi:~/Pimoroni/inky/examples/7color $ cat /etc/*-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian

version of inky is 1.3.2

running the identify.py:
ubuntu@raspberrypi:~/Pimoroni/inky/examples $ python identify.py
Found: 7-Colour (UC8159)
Display: 600x448
Color: None
PCB Variant: 1.2
Display Variant: 14
Time: b'2021-02-08 14:39:18.8'

SPI and I2C are activated

Could you please provide some help on this?

Thank you in advance

**Comment by ageeandakeyboard** [comment]
After some testing it looks as though this error has now been solved. Thanks
