### ISSUE TITLE
Yahoo API is not working now

### ISSUE THREAD

**Issue by LiyangDotWebsite** [pimoroni/inky#15]
> Important EOL Notice: As of Thursday, Jan. 3, 2019, the weather.yahooapis.com and query.yahooapis.com for Yahoo Weather API will be retired. 
> To continue using our free Yahoo Weather APIs, use https://weather-ydn-yql.media.yahoo.com/forecastrss. Contact yahoo-weather-ydn-api@oath.com for credentials to onboard to this free Yahoo Weather API service.
From [yahoo](https://developer.yahoo.com/weather/?guccounter=1)

**Comment by mfraser** [comment]
I've rewritten this using OpenWeatherMap as https://github.com/mfraser/weather-phat. Let me know if there are problems. You will need to create an api key at OpenWeatherMap and add it here api = "".

**Comment by Gadgetoid** [comment]
Most of our weather examples have been tweaked to use darksky.net, but thank you!

I'd love to build a platform that can potentially support *all* weather APIs and *all* output displays.
