### ISSUE TITLE
Feature request: faster monochrome updates on Inky Impression

### ISSUE THREAD

**Issue by joel0** [pimoroni/inky#155]
Would it be possible to do less comprehensive display refreshing to display black & white while skipping all other 5 colors?

My use case updates the display every 5 minutes and only needs color on rare occasions.  I use a large font for viewing from a distance, so I wouldn't even mind if it leads to some visible artifacts.

I'm not sure whether this is technically possible with the Impression hardware, but seeing how many other e-ink products on the market have options to tradeoff speed for quality, I figured it's worth asking at least.

**Comment by helgibbons** [comment]
We've not found a way to do this with the seven colour displays I'm afraid - as I understand it the screen driver chip on these displays mandates a full clear cycle every time so we're not able to modify the refresh behaviour.

**Comment by joel0** [comment]
Thank you for taking the time to answer my question. :)
