### ISSUE TITLE
Use on any non-Pi machines?

### ISSUE THREAD

**Issue by DanielArnett** [pimoroni/inky#172]
Does anyone know if this driver can be used on any non-Pi devices? If I have something similar that has SPI pins (like a beaglebone or jetson) is it able to connect to the inky?

Thank you,

**Comment by SpencerWF** [comment]
There should be any reason you can't use it on any device, but you will need to reverse-engineer the communication that's happening in the pi libraries as I don't know if anyone has done this yet.

**Comment by Gadgetoid** [comment]
Migrating this library from RPi.GPIO over to gpiod - which is on my TODO list - should very much help with that. The spidev/smbus libraries are pretty standard already, but Pi GPIO has been the exception.

**Comment by DanielArnett** [comment]
Thank you both for the feedback. I don't have an immediate need for this (Pi ended up being fine for my project), but it might one day be necessary. If I end up having to do this I'll make sure to submit a PR here.

**Comment by Gadgetoid** [comment]
gpiod support is now merged :partying_face: 

I don't actually *have* any alternate boards to test on, but in theory the driver should now work anywhere that has gpiod.
