### ISSUE TITLE
error: externally-managed-environment

### ISSUE THREAD

**Issue by ChopsKingsland** [pimoroni/inky#177]
I can't seem to install this package.

I've tried both manually doing `pip3 install` and using `install.sh`, and both give the same error...

<img width="1511" alt="image" src="https://github.com/pimoroni/inky/assets/18499854/00c66e2e-3183-48ae-9c73-17bd1cf724c3">

I also tried `pip3 install` with `--break-system-packages` and it failed for a different reason...

**Comment by Gadgetoid** [comment]
Read the error message 😆

Also, see this absolute wall of text I've been cobbling together about this problem and how we might fix it via our install scripts: https://github.com/pimoroni/boilerplate-python/pull/13

Now, if you'd join me in an anguished scream... 😭

**Comment by helgibbons** [comment]
Closing this one as we've now merged the new installer into main - it should now attempt to set up a virtual environment for you, if you don't have one.

There's updated install instructions in the readme: https://github.com/pimoroni/inky/blob/main/README.md

I've also updated our Inky pHAT and wHAT Learn Guides:
https://learn.pimoroni.com/article/getting-started-with-inky-phat
https://learn.pimoroni.com/article/getting-started-with-inky-what
