### ISSUE TITLE
Forcing black and white only on 7 color.

### ISSUE THREAD

**Issue by owardlaw** [pimoroni/inky#178]
Could I force black and white only on the 7-color display? I want to improve refresh times in certain cases and limit the display from considering other colors when it refreshes an image.

**Comment by Gadgetoid** [comment]
Unfortunately not. 7-colour does what 7-colour wants and does not have any configurable LUTs/waveforms.

**Comment by owardlaw** [comment]
@Gadgetoid Ahhh thanks for the reply, I guess I will be purchasing the 4" black and white display then.
