### ISSUE TITLE
Partial Update or Single Pixel Update for all Inky Impression 

### ISSUE THREAD

**Issue by brainlessboy** [pimoroni/inky#179]
it would be amazing to enable
- partial update (square region)
- single pixel direct update 

even if due to the tech used there might be inperfect results (blurred pixels) 
this would enable to add more interaction to projects, text input, other interaction that would need small portion of the screen to update on input

**Comment by helgibbons** [comment]
The clean cycle is mandated by the display controller on the seven colour EInks - we've not found any ways of modifying the refresh behaviour at all with these I'm afraid.
