### ISSUE TITLE
It didn't blow up

### ISSUE THREAD

**Issue by johnstaveley** [pimoroni/inky#187]
When running this command:

curl https://get.pimoroni.com/inky | bash

You are told that the library should only be installed on PI5's. However in the item description:

https://shop.pimoroni.com/products/inky-impression-7-3?variant=40512683376723

There is nothing about the screen being restricted to raspberry pi 5s.

So either fix the item description or the item library.

**Comment by Gadgetoid** [comment]
Where in the command output does it mention Pi 5?

**Comment by johnstaveley** [comment]
It is written in red just before you have to type yes to confirm you want to go ahead

**Comment by johnstaveley** [comment]
I tested this on a Pi4

**Comment by johnstaveley** [comment]
Ah yes, sorry. I read that as 05, oops

**Comment by Gadgetoid** [comment]
No worries, ironically the Pi 5 is where it *breaks* 😢
