### ISSUE TITLE
Add fonts to setup.py

### ISSUE THREAD

**Issue by sandyjmacdonald** [pimoroni/inky#2]
The following fonts are required by the examples, and should probably be installed alongside the library:

- font_hanken_grotesk
- font_intuitive
- font_fredoka_one
- font_source_serif_pro
- font_source_sans_pro

The latter two need to be added to the Python fonts library

**Comment by Gadgetoid** [comment]
Since they're dependencies of the examples and not the library itself, I've added htem into the `get` install script.
