### ISSUE TITLE
Add option to skip "busy wait" during update

### ISSUE THREAD

**Issue by Gadgetoid** [pimoroni/inky#26]
The `show()` method could use a `skip_busy_wait` for people who want to stick to simple single-threaded code but do something else while the display is updating.

See: https://forums.pimoroni.com/t/is-it-safe-to-run-inky-phat-screen-writes-in-a-separate-thread/9969

**Comment by bcrowell** [comment]
I would also find this feature very helpful.

**Comment by bcrowell** [comment]
Oh, I see -- I looked at the code, and this has already been implemented. Tested it and it works, yay! So maybe the issue should be closed and this feature should be mentioned in the documentation.
