### ISSUE TITLE
SPI speed set to 488KHz

### ISSUE THREAD

**Issue by spaceneedle** [pimoroni/inky#30]
Is there any reason why the SPI speed is set so slow? The display controller supports up to 20MHz.

**Comment by Gadgetoid** [comment]
This traces back to a commit against the original Inky pHAT library when adding support for V2 displays: https://github.com/pimoroni/inky-phat/commit/3a9d2d5874233f9c9573bde87af4a880b0af72dd#diff-aeef2c01415135a1e221591a3fa15198

It doesn't really shed much light onto *why* it's there (although we could guess), but now it's very much one of those "if it ain't broke, don't fix it" situations.
