### ISSUE TITLE
Setting border to red / yellow - is it possible?

### ISSUE THREAD

**Issue by gauntface** [pimoroni/inky#42]
I tried setting the border to red in one of the examples and found that it didn't work, only black and white work - is that expected?

**Comment by Gadgetoid** [comment]
As far as I'm aware it should be possible to set the border to Red on all Red/Black/White displays and Yellow on all Yellow/Black/White displays. This is explicitly supported in the library, but it's possible that there's a bug preventing it from working properly. This warrants some investigation.

What version/type of Inky pHAT do you have?

**Comment by gauntface** [comment]
I have an inky what red, not sure what version - how can I tell?

**Comment by dustinrb** [comment]
I'm having the same issue. I'm using a black/yellow SSD1608 variant. Looking through the source code I see that the border color is set in the Inky class, but the WRITE_BORDER command is never given to the board in the _update method.

**Comment by jerbzz** [comment]
@dustinrb https://github.com/pimoroni/inky/issues/100#issuecomment-787552450
