### ISSUE TITLE
Using the weather-that.py script in crontab

### ISSUE THREAD

**Issue by wildestpixel** [pimoroni/inky#44]
Had to edit lines 131 and 135

from (131)
`img = Image.open("resources/backdrop.png")`
to
`img = Image.open("/home/pi/Pimoroni/inky/examples/phat/resources/backdrop.png")`

and 

from (135)
`for icon in glob.glob("resources/icon-*.png"):`
to
`for icon in glob.glob("/home/pi/Pimoroni/inky/examples/phat/resources/icon-*.png"):`

in order to run a crontab schedule of 
`*/10 * * * * python ~/Pimoroni/inky/examples/phat/weather-phat.py --colour "red"`

as suggested in the getting started page on Pimoroni web

**Comment by Gadgetoid** [comment]
Thanks! I've added a couple of commits that should fix this for the phat examples so they don't need to be modified with fixed paths.
