### ISSUE TITLE
problems with the installation of the dependencies

### ISSUE THREAD

**Issue by kompas1** [pimoroni/inky#56]
So it's me again, so I tried a clean reinstall with the script: curl -sSL https://get.pimoroni.com/inky | bash

the first few things get installed without any problem but then at some point i get this:

Checking for additional software...
python-geocoder is required
Installing python-geocoder...
E: Unable to locate package python-geocoder
Apt failed to install python-geocoder!
Falling back on pypi...
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting geocoder
  Downloading https://files.pythonhosted.org/packages/4f/6b/13166c909ad2f2d76b929a4227c952630ebaf0d729f6317eb09cbceccbab/geocoder-1.38.1-py2.py3-none-any.whl (98kB)
    100% |████████████████████████████████| 102kB 425kB/s 
Collecting click (from geocoder)
  Downloading https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl (82kB)
    100% |████████████████████████████████| 92kB 552kB/s 
Collecting ratelim (from geocoder)
  Downloading https://files.pythonhosted.org/packages/f2/98/7e6d147fd16a10a5f821db6e25f192265d6ecca3d82957a4fdd592cad49c/ratelim-0.1.6-py2.py3-none-any.whl
Collecting requests (from geocoder)
  Downloading https://files.pythonhosted.org/packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests-2.24.0-py2.py3-none-any.whl (61kB)
    100% |████████████████████████████████| 71kB 550kB/s 
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from geocoder) (1.12.0)
Collecting future (from geocoder)
  Downloading https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (829kB)
    100% |████████████████████████████████| 829kB 91kB/s 
Collecting decorator (from ratelim->geocoder)
  Downloading https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
Collecting idna<3,>=2.5 (from requests->geocoder)
  Downloading https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 536kB/s 
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->geocoder)
  Downloading https://files.pythonhosted.org/packages/9f/f0/a391d1463ebb1b233795cabfc0ef38d3db4442339de68f847026199e69d7/urllib3-1.25.10-py2.py3-none-any.whl (127kB)
    100% |████████████████████████████████| 133kB 489kB/s 
Collecting certifi>=2017.4.17 (from requests->geocoder)
  Downloading https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl (156kB)
    100% |████████████████████████████████| 163kB 410kB/s 
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python2.7/dist-packages (from requests->geocoder) (3.0.4)
Building wheels for collected packages: future
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /root/.cache/pip/wheels/8b/99/a0/81daf51dcd359a9377b110a8a886b3895921802d2fc1b2397e
Successfully built future
Installing collected packages: click, decorator, ratelim, idna, urllib3, certifi, requests, future, geocoder
Successfully installed certifi-2020.6.20 click-7.1.2 decorator-4.4.2 future-0.18.2 geocoder-1.38.1 idna-2.10 ratelim-0.1.6 requests-2.24.0 urllib3-1.25.10
python3-geocoder is required
Installing python3-geocoder...

and not only with the python3-geocoder
also with: python-beautifulsoup4, with python3-beautifulsoup4, with python-fonts, with python3-fonts, python-font_hanken_grotesk, python3-font_hanken_grotesk, and every other font too and also the python-wikiquotes and python3-wikiquotes

does anyone know why?

**Comment by Gadgetoid** [comment]
The bash installer always tries to use `apt` to install `pythonX-<packagename>` first, and fails back to pip.

The reason for this may now be legacy and unecessary, but it's basically to avoid hitting any compiler errors, or horrid long compile times associated with source-distribution packages available on PyPi.

I think PiWheels might render this practice obsolete.

As long as these packages have been installed by pip, and the library works, then these errors can be ignored.

They do- however- look to be an unecessarily slow alternative to what could be a single `sudo pip install <list of packages>" command.
