### ISSUE TITLE
Confused about which model I recieved

### ISSUE THREAD

**Issue by sjsteer** [pimoroni/inky#60]
Hello, I recently purchased the red Inky pHat red (similar to use issue #58) however upon downloading the packages I am faced with a similar issue. There is one electrode on the front of module

![image](https://user-images.githubusercontent.com/46882791/92341053-e3f48100-f0ff-11ea-8ef4-9012e1c11bf4.png)

I've attempted to print read_eeprom() but it returns None. 

I honestly have no idea which display has been sent to me and I've contacted the supplier to try and shed some light on the issue.

**Comment by Gadgetoid** [comment]
Try running `sudo i2cdetect -y 1` to see if you can see an EEPROM show up. You should see something like this:

```
pi@raspberrypi:~ $ sudo i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: 50 -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

**Comment by sjsteer** [comment]
Thank you @Gadgetoid, after checking the connections and reinstalling Rasbpian lite it works.

![image](https://user-images.githubusercontent.com/46882791/92421297-38106b80-f1bb-11ea-85b0-2fe734a2532f.png)
![image](https://user-images.githubusercontent.com/46882791/92421324-58402a80-f1bb-11ea-9c9c-41d54a4ab615.png)

Thank you!
