### ISSUE TITLE
SPI mode for the Inky

### ISSUE THREAD

**Issue by Axel-Jacobsen** [pimoroni/inky#62]
Hello!

I am looking to use an Inky as well as another device on SPI. Looking through your code, you use SPI bus 0, which for the Pi, only allows for SPI modes 1 and 3 (i.e. CPOL, CPHA = 0,1 or 1,1).

Is your device able to operate on bus 1, which only allows for SPI modes 0 and 2 (i.e. CPOL, CPHA = 0,0 or 1,0)?

Cheers!

**Comment by Gadgetoid** [comment]
I don't actually know- although it's easy enough to bitbang SPI on any pins, making the modes supported by the hardware somewhat academic.
