### ISSUE TITLE
GPIO Pins with Inky

### ISSUE THREAD

**Issue by felixloftus** [pimoroni/inky#98]
Hi, I have the pimoroni Inky Phat and I'd like to know if I can still access the GPIO pins that this screen doesn't use. I'd like to add buttons and a rotary encoder to my device. I'm a bit confused because I know the screen doesn't use all the GPIO pins but it seems to connect to all of them... any advice would be welcomed :)

**Comment by bablokb** [comment]
Check https://pinout.xyz/pinout/inky_phat for the pinout. You can use the other pins without problems. BTW, I soldered long pins (20mm) half-way to a Zero-W, so I can plug in the zero to the inky and still have all pins available additionally on the other side. You can see some images [here](https://github.com/bablokb/pi-e-ink-daily/blob/master/Inky-Impression-Frame/Readme.md). This is for the big Inky-Impression, but using long pins should work also for the pHat. Another solution would be to use a pin-multiplexer, e.g. Pimoroni's [Pico Hat Hacker](url), or the [butterfly](https://www.tindie.com/products/8086net/butterfly/) available from Tindie.
